-- begin SAMARAMUSOR_CONTRACT
alter table SAMARAMUSOR_CONTRACT add constraint FK_SAMARAMUSOR_CONTRACT_ON_ORGANIZATION foreign key (ORGANIZATION_ID) references SAMARAMUSOR_ORGANIZATION(ID)^
create index IDX_SAMARAMUSOR_CONTRACT_ON_ORGANIZATION on SAMARAMUSOR_CONTRACT (ORGANIZATION_ID)^
-- end SAMARAMUSOR_CONTRACT
-- begin SAMARAMUSOR_ORGANIZATION
create unique index IDX_SAMARAMUSOR_ORGANIZATION_UNIQ_INN on SAMARAMUSOR_ORGANIZATION (INN) ^
-- end SAMARAMUSOR_ORGANIZATION
